version: "3"
services:
  jenkins_container:
    build:
      context: ./DockerfileJenkins
    restart: always
    image: jenkins/jenkins:lts-jdk11
    ports:
      - 80:80
    user: root
    volumes:
      - /home/azure_jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
